spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:s7ENZB2f9qffq6os25pStVNO_-GfaWhrelpxMD1trnKYO2iX@5c5072cf-e389-4463-b316-e688af864593.asia-south1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}